name: Monitor Project Column Changes

on:
  #  schedule:
  #    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch previous state
        id: load_previous_state
        run: |
          chmod +x .github/scripts/check-or-create-state.sh
          .github/scripts/check-or-create-state.sh

      - name: Fetch project items via GraphQL
        id: fetch_current_state
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          chmod +x .github/scripts/stringify.sh
          query=$(cat .github/graphQL/get-card-detail.graphql | .github/scripts/stringify.sh)
          query="${query//PARAMETER/PVTI_lADOCyNzbs4ArXwDzgUZUCA}"
          response=$(curl -s -X POST -H "Authorization: bearer $GITHUB_TOKEN" -H "Content-Type: application/json" \
          -d "{\"query\": \"$query\"}" https://api.github.com/graphql)
          echo "$response" > current_state.json
        shell: /usr/bin/bash -e {0}
        
      - name: Compare project state and detect changes
        id: detect_changes
        run: |
          chmod +x .github/scripts/compare-state.sh
          .github/scripts/compare-state.sh

      - name: Save current state
        if: env.changed == 'true'
        run: |
          chmod +x .github/scripts/copy-and-push.sh
          .github/scripts/copy-and-push.sh
